services:
  redis:
    container_name: redis
    image: redis:alpine
    restart: on-failure
    networks:
      - pg

  directus:
    container_name: directus
    image: directus/directus:latest
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: $DIRECTUS_LIMITS_CPUS
          memory: $DIRECTUS_LIMITS_MEMORY
      restart_policy:
        condition: $DIRECTUS_RESTART_CONDITION
        delay: $DIRECTUS_RESTART_DELAY
        max_attempts: $DIRECTUS_RESTART_MAX_ATTEMPTS
        window: $DIRECTUS_RESTART_WINDOW
    networks:
      - nginx
      - pg
    ports:
      - 8055:8055
    volumes:
      - directus:/directus
      # - ./bind/database:/directus/database
      # - ./bind/uploads:/directus/uploads
      # - ./bind/extensions:/directus/extensions

networks:
  nginx:
    external: true
  pg:
    external: true

volumes:
  directus:
    # external: true
