services:
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    networks:
      - redis
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping | grep PONG']
      interval: 10s
      timeout: 5s
      retries: 5

  directus:
    container_name: directus
    image: directus/directus:latest
    env_file: .env
    depends_on:
      redis:
        condition: service_healthy
      # postgres:
      #   condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: $DIRECTUS_LIMITS_CPUS
          memory: $DIRECTUS_LIMITS_MEMORY
      restart_policy:
        condition: $DIRECTUS_RESTART_CONDITION
        delay: $DIRECTUS_RESTART_DELAY
        max_attempts: 5
        window: '1h'
    networks:
      - nginx
      - pg
      - redis
    ports:
      - 8055:8055
    volumes:
      - directus:/directus
      # - ./bind/database:/directus/database
      # - ./bind/uploads:/directus/uploads
      # - ./bind/extensions:/directus/extensions

networks:
  nginx:
    external: true
  pg:
    external: true
  redis:
    external: true

volumes:
  directus:
    # external: true
