services:
  cache:
    container_name: cache-redis-alpine
    image: redis:alpine
    networks:
      - net_pg

  directus:
    container_name: directus
    image: directus/directus:latest
    env_file: .env
    networks:
      - net_pg
    ports:
      - 8055:8055
    volumes:
      - ./bind/database:/directus/database
      - ./bind/uploads:/directus/uploads
      - ./bind/extensions:/directus/extensions
    depends_on:
      - cache

networks:
  net_pg:
    external: true
