services:
  redis:
    container_name: redis
    image: redis:alpine
    restart: on-failure
    networks:
      - pg

  directus:
    container_name: directus
    image: directus/directus:latest
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 150m
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 2m
    env_file: .env
    networks:
      - nginx
      - pg
    ports:
      - 8055:8055
    volumes:
      - directus:/directus
      # - ./bind/database:/directus/database
      # - ./bind/uploads:/directus/uploads
      # - ./bind/extensions:/directus/extensions
    depends_on:
      - redis

networks:
  nginx:
    external: true
  pg:
    external: true

volumes:
  directus:
    # external: true
