services:
  cache:
    container_name: cache-redis-alpine
    image: redis:alpine
    networks:
      - pg

  directus:
    container_name: directus-alpine
    image: directus/directus:latest
    restart: on-failure
    env_file: .env
    networks:
      - nginx
      - pg
    ports:
      - 8055:8055
    volumes:
      - directus:/directus
      # - ./bind/database:/directus/database
      # - ./bind/uploads:/directus/uploads
      # - ./bind/extensions:/directus/extensions
    depends_on:
      - cache

networks:
  nginx:
    external: true
  pg:
    external: true

volumes:
  directus:
    external: true
